// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoExpandTextareaController from "./auto_expand_textarea_controller"
application.register("auto-expand-textarea", AutoExpandTextareaController)

import AutosubmitselectController from "./autosubmitselect_controller"
application.register("autosubmitselect", AutosubmitselectController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MaskController from "./mask_controller"
application.register("mask", MaskController)

import UploadController from "./upload_controller"
application.register("upload", UploadController)
